### ISSUE TITLE
Add actions component ?

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/kanbasu#44]
A component that list buttons inline on large screens but stack them as blocks on mobiles. The following code works just fine but lacks flexibility in terms of spacings and media query choice.

To be potentially split in two components: responsive lists (switch between inline and block) and responsive block buttons.

```scss
.actions {
  @extend %list;

  @include media('xs', $breakpoints-desc) {
    .btn {
      display: block;
      width: 100%;
    }

    > li:not(:last-child) {
      margin-bottom: $spacing-unit-small;
    }
  }

  @include media('sm') {
    > li {
      display: inline-block;

      &:not(:last-child) {
        margin-right: $spacing-unit-default;
      }
    }
  }
}
```
